export const MAX_DRAFTING_INPUT_CHARS = 25000

export const EMAIL_DRAFTING_PROJECT_NAME = 'Email Drafting Requests'

export const EMAIL_DRAFTING_INBOUND_ADDRESS = 'noreply@patentnest.ai'

export const EMAIL_DRAFTING_DOWNLOAD_TTL_DAYS = 7

export const EMAIL_DRAFTING_MAX_REQUESTS_PER_HOUR = 3

export const EMAIL_DRAFTING_MAX_CONCURRENT_WORKERS = 2

export const EMAIL_DRAFTING_STALE_LOCK_MINUTES = 15

export const AUTO_DRAFTING_BULK_RECIPIENT = 'bulk-auto-drafting@patentnest.local'

export const AUTO_DRAFTING_MAX_UPLOAD_ROWS = 25

export const EMAIL_DRAFTING_PROGRESS: Record<string, number> = {
  RECEIVED: 5,
  VALIDATING: 10,
  PARSING: 20,
  INITIALIZING: 25,
  NORMALIZING: 35,
  CLAIMS_SETUP: 45,
  PRIOR_ART_CONTEXT: 55,
  COMPONENTS: 65,
  FIGURES: 75,
  DRAFTING: 85,
  REVIEW: 92,
  EXPORT: 97,
  DELIVERED: 100,
  DELIVERED_WITH_WARNINGS: 100,
  REJECTED: 100,
  FAILED: 100,
}

export const EMAIL_DRAFTING_ALLOWED_TEXT_EXTENSIONS = ['.docx', '.txt', '.md'] as const
