/**
 * Unified Idea Bank Funnel Service
 * 
 * This service provides a unified pipeline for generating and validating ideas
 * from prior art analysis. It's used by both:
 * - Drafting Pipeline (Prior Art Review)
 * - Novelty Search Pipeline (Stage 4 Report)
 * 
 * Architecture:
 * ┌─────────────────────────────────────────────────────────────────────┐
 * │              PRIOR ART ANALYSIS RESULTS                             │
 * │    (from Drafting Pipeline OR Novelty Search Pipeline)              │
 * └──────────────────────────────┬──────────────────────────────────────┘
 *                                │
 *            ┌───────────────────┼───────────────────┐
 *            │                                       │
 *            ▼                                       ▼
 *     ┌──────────────┐                      ┌──────────────┐
 *     │  STREAM A    │                      │  STREAM B    │
 *     │ Cross-Domain │   (parallel)         │  Technology  │
 *     │ Applications │                      │ Combinations │
 *     └──────┬───────┘                      └──────┬───────┘
 *            │                                     │
 *            └─────────────┬───────────────────────┘
 *                          │
 *                          ▼
 *               ┌────────────────────────────────┐
 *               │         STREAM C               │
 *               │    LLM VALIDATION LAYER        │
 *               │  (Judge: approve or reject)    │
 *               └────────────────┬───────────────┘
 *                                │
 *               ┌────────────────┼────────────────┐
 *               │                                 │
 *               ▼                                 ▼
 *        ┌──────────┐                      ┌──────────┐
 *        │ APPROVED │                      │ REJECTED │
 *        │ → Idea   │                      │ → Logged │
 *        │   Bank   │                      │   Only   │
 *        └──────────┘                      └──────────┘
 */

import { llmGateway } from './metering/gateway';
import { IdeaBankService } from './idea-bank-service';
import { prisma } from './prisma';
import crypto from 'crypto';

// ============================================================================
// INTERFACES
// ============================================================================

/**
 * Unified interface for prior art analysis from both pipelines
 */
export interface PriorArtAnalysisItem {
  pn: string;                    // Patent number
  title: string;                 // Patent title
  abstract?: string;             // Patent abstract (optional)
  relevance: number;             // 0-1 relevance score
  novelty_threat: 'anticipates' | 'obvious' | 'adjacent' | 'remote';
  summary: string;               // Brief analysis summary
  detailedAnalysis: {
    summary: string;
    relevant_parts: string[];    // Overlapping elements
    irrelevant_parts: string[];  // Non-overlapping elements
    novelty_comparison: string;  // What makes our invention novel
  };
}

/**
 * Input for the Idea Bank Funnel from either pipeline
 */
export interface IdeaFunnelInput {
  source: 'drafting_pipeline' | 'novelty_search';
  
  // Invention context
  invention: {
    title: string;
    abstract?: string;
    claims?: string;
    features?: string[];
    searchQuery?: string;
  };
  
  // Prior art analysis in unified format
  priorArtAnalysis: PriorArtAnalysisItem[];
  
  // Tracking metadata
  userId: string;
  patentId?: string;      // For drafting pipeline
  sessionId?: string;     // For drafting pipeline
  searchRunId?: string;   // For novelty search pipeline
  runId?: string;         // For drafting prior art run
  
  // Request headers for LLM calls
  requestHeaders?: Record<string, string>;
}

/**
 * Raw idea generated by Stream A or B
 */
interface RawIdea {
  title: string;
  description: string;
  rationale: string;
  target_domain?: string;
  combined_tech?: string;
  tags: string[];
  source_stream: 'cross_domain' | 'tech_combination';
}

/**
 * Validated idea after Stream C review
 */
interface ValidatedIdea extends RawIdea {
  approved: boolean;
  validation: {
    feasibility_score: number;
    novelty_score: number;
    coherence_score: number;
    overall_score: number;
    verdict: 'APPROVED' | 'REJECTED';
    rejection_reason?: string;
    improvement_suggestions?: string;
  };
}

/**
 * Result of the funnel processing
 */
export interface IdeaFunnelResult {
  success: boolean;
  stats: {
    generated: number;
    approved: number;
    rejected: number;
  };
  approvedIdeas: ValidatedIdea[];
  rejectedIdeas: ValidatedIdea[];
  errors?: string[];
}

// ============================================================================
// STREAM A: CROSS-DOMAIN APPLICATIONS
// ============================================================================

const STREAM_A_PROMPT = `You are a technology transfer specialist who finds novel applications for inventions in UNEXPECTED domains.

INVENTION:
Title: {invention_title}
{invention_context}

WHAT MAKES THIS INVENTION UNIQUE (from prior art analysis):
{novelty_gaps}

DOMAINS WHERE SIMILAR PATENTS EXIST (avoid these or find different applications):
{existing_domains}

YOUR TASK:
Find 3-4 industries/domains where:
1. They have an UNSOLVED problem that matches our invention's core capability
2. The application would be genuinely novel (not covered by existing patents)
3. The solution would be commercially valuable and technically feasible

For each idea, provide:
- title: Concise technical title (max 12 words)
- description: How our technology solves the problem in this new domain (2-3 sentences)
- rationale: Why this hasn't been done before and why it would work (1-2 sentences)
- target_domain: The industry/field this applies to
- tags: [target_domain, technology_type, application_type]

IMPORTANT CONSTRAINTS:
- Ideas must be achievable with current technology
- No physics-defying concepts (perpetual motion, free energy, etc.)
- Focus on practical commercial applications
- Be specific about the mechanism, not just "use AI" or "use blockchain"

Return ONLY valid JSON:
{
  "cross_domain_ideas": [
    {
      "title": "...",
      "description": "...",
      "rationale": "...",
      "target_domain": "...",
      "tags": ["...", "..."]
    }
  ]
}`;

// ============================================================================
// STREAM B: TECHNOLOGY COMBINATIONS
// ============================================================================

const STREAM_B_PROMPT = `You are an innovation strategist who creates breakthrough inventions by combining technologies.

INVENTION:
Title: {invention_title}
{invention_context}

CORE CAPABILITY OF THIS INVENTION:
{core_capability}

PRIOR ART GAPS (what our invention does that others don't):
{novelty_gaps}

YOUR TASK:
Propose 3-4 hybrid inventions that combine our core technology with emerging technologies.
Each combination must:
1. Solve a problem that NEITHER technology alone can solve
2. Create synergy (1+1=3, not just 1+1=2)
3. Be technically feasible with current engineering knowledge
4. NOT exist in the prior art analyzed

EMERGING TECHNOLOGIES TO CONSIDER COMBINING WITH:
- Edge AI / On-device ML
- IoT sensors and connectivity
- Advanced materials (graphene, metamaterials, smart polymers)
- Biotechnology / Synthetic biology
- AR/VR/Mixed Reality
- Robotics / Automation
- Energy harvesting / Storage
- Quantum sensing (not computing)
- 3D/4D printing
- Blockchain / Distributed systems (only if genuinely useful)

For each combination:
- title: Concise technical title (max 12 words)
- description: How the combination works and what new capability it creates (2-3 sentences)
- rationale: Why this combination is synergistic and novel (1-2 sentences)
- combined_tech: The emerging technology being combined
- tags: [our_tech_domain, combined_tech_domain, application]

IMPORTANT:
- Don't force combinations - only propose if there's genuine synergy
- Be specific about the mechanism of combination
- Avoid buzzword combinations without substance

Return ONLY valid JSON:
{
  "tech_combination_ideas": [
    {
      "title": "...",
      "description": "...",
      "rationale": "...",
      "combined_tech": "...",
      "tags": ["...", "..."]
    }
  ]
}`;

// ============================================================================
// STREAM C: VALIDATION LAYER (LLM JUDGE)
// ============================================================================

const STREAM_C_VALIDATION_PROMPT = `You are a senior patent examiner and venture capitalist evaluating invention ideas.
Your job is to CRITICALLY ASSESS ideas - be skeptical, not encouraging.

IDEAS TO EVALUATE:
{ideas_json}

ORIGINAL INVENTION CONTEXT:
{invention_context}

For EACH idea, evaluate on these criteria (score 0-10):

1. FEASIBILITY: Can this be built with CURRENT technology?
   - 0-3: Violates physics, requires non-existent technology, or is vague hand-waving
   - 4-6: Possible but significant engineering challenges remain unclear
   - 7-10: Achievable with existing knowledge and reasonable R&D

2. NOVELTY: Is this actually new and non-obvious?
   - 0-3: Already exists, obvious combination, or just buzzwords
   - 4-6: Incremental improvement, may face obviousness challenges
   - 7-10: Genuinely novel approach with clear differentiation

3. COHERENCE: Is the description clear and technically sound?
   - 0-3: Vague, contradictory, or buzzword salad
   - 4-6: Understandable but lacks technical specifics
   - 7-10: Clear, specific, actionable technical description

APPROVAL CRITERIA:
- APPROVED: Average score >= 6.0 AND no individual score below 4
- REJECTED: Otherwise

For rejected ideas, explain WHY and suggest how it could be improved.

Return ONLY valid JSON:
{
  "validations": [
    {
      "idea_title": "...",
      "feasibility_score": N,
      "feasibility_reason": "...",
      "novelty_score": N,
      "novelty_reason": "...",
      "coherence_score": N,
      "coherence_reason": "...",
      "overall_score": N,
      "verdict": "APPROVED" | "REJECTED",
      "rejection_reason": "..." (if rejected),
      "improvement_suggestions": "..." (if rejected)
    }
  ]
}`;

// ============================================================================
// IDEA BANK FUNNEL SERVICE
// ============================================================================

export function isIdeaBankGenerationEnabled(): boolean {
  // Disabled by default. Set either env var to "true" to re-enable idea-bank generation.
  return process.env.IDEA_BANK_GENERATION_ENABLED === 'true' ||
    process.env.IDEA_BANK_FUNNEL_ENABLED === 'true';
}

export function isIdeaBankFunnelEnabled(): boolean {
  return isIdeaBankGenerationEnabled();
}

export class IdeaBankFunnelService {
  private ideaBankService: IdeaBankService;
  
  constructor() {
    this.ideaBankService = new IdeaBankService();
  }
  
  /**
   * Main entry point - process ideas through the funnel
   * This runs asynchronously and doesn't block the caller
   */
  async processIdeasAsync(input: IdeaFunnelInput): Promise<void> {
    if (!isIdeaBankFunnelEnabled()) {
      console.log(`[IdeaBankFunnel] Disabled; skipping async funnel for ${input.source}`);
      return;
    }

    // Fire and forget - don't await
    this.processFunnel(input).catch(err => {
      console.error('[IdeaBankFunnel] Async processing failed:', err);
    });
  }
  
  /**
   * Process the funnel synchronously (for testing or when result is needed)
   */
  async processFunnel(input: IdeaFunnelInput): Promise<IdeaFunnelResult> {
    if (!isIdeaBankFunnelEnabled()) {
      console.log(`[IdeaBankFunnel] Disabled; skipping funnel for ${input.source}`);
      return {
        success: false,
        stats: { generated: 0, approved: 0, rejected: 0 },
        approvedIdeas: [],
        rejectedIdeas: [],
        errors: ['Idea Bank Funnel is disabled']
      };
    }

    console.log(`[IdeaBankFunnel] Starting funnel for ${input.source}`);
    console.log(`[IdeaBankFunnel] Invention: ${input.invention.title}`);
    console.log(`[IdeaBankFunnel] Prior art items: ${input.priorArtAnalysis.length}`);
    
    const errors: string[] = [];
    let allRawIdeas: RawIdea[] = [];
    
    // Build context from prior art analysis
    const noveltyGaps = this.extractNoveltyGaps(input.priorArtAnalysis);
    const existingDomains = this.extractDomains(input.priorArtAnalysis);
    const coreCapability = this.extractCoreCapability(input);
    
    // =========================================================================
    // STREAM A + B: Run in parallel
    // =========================================================================
    console.log('[IdeaBankFunnel] Running Stream A (Cross-Domain) and Stream B (Tech Combinations) in parallel...');
    
    const [streamAResult, streamBResult] = await Promise.allSettled([
      this.runStreamA(input, noveltyGaps, existingDomains),
      this.runStreamB(input, noveltyGaps, coreCapability)
    ]);
    
    // Collect results from Stream A
    if (streamAResult.status === 'fulfilled' && streamAResult.value.length > 0) {
      console.log(`[IdeaBankFunnel] Stream A generated ${streamAResult.value.length} ideas`);
      allRawIdeas.push(...streamAResult.value);
    } else if (streamAResult.status === 'rejected') {
      console.error('[IdeaBankFunnel] Stream A failed:', streamAResult.reason);
      errors.push(`Stream A failed: ${streamAResult.reason}`);
    }
    
    // Collect results from Stream B
    if (streamBResult.status === 'fulfilled' && streamBResult.value.length > 0) {
      console.log(`[IdeaBankFunnel] Stream B generated ${streamBResult.value.length} ideas`);
      allRawIdeas.push(...streamBResult.value);
    } else if (streamBResult.status === 'rejected') {
      console.error('[IdeaBankFunnel] Stream B failed:', streamBResult.reason);
      errors.push(`Stream B failed: ${streamBResult.reason}`);
    }
    
    if (allRawIdeas.length === 0) {
      console.log('[IdeaBankFunnel] No ideas generated from streams A and B');
      return {
        success: false,
        stats: { generated: 0, approved: 0, rejected: 0 },
        approvedIdeas: [],
        rejectedIdeas: [],
        errors: errors.length > 0 ? errors : ['No ideas generated']
      };
    }
    
    // =========================================================================
    // STREAM C: Validation Layer
    // =========================================================================
    console.log(`[IdeaBankFunnel] Running Stream C (Validation) on ${allRawIdeas.length} ideas...`);
    
    let validatedIdeas: ValidatedIdea[] = [];
    try {
      validatedIdeas = await this.runStreamC(input, allRawIdeas);
      console.log(`[IdeaBankFunnel] Stream C validated ${validatedIdeas.length} ideas`);
    } catch (err) {
      console.error('[IdeaBankFunnel] Stream C failed:', err);
      errors.push(`Stream C validation failed: ${err}`);
      // If validation fails, reject all ideas
      validatedIdeas = allRawIdeas.map(idea => ({
        ...idea,
        approved: false,
        validation: {
          feasibility_score: 0,
          novelty_score: 0,
          coherence_score: 0,
          overall_score: 0,
          verdict: 'REJECTED' as const,
          rejection_reason: 'Validation service unavailable'
        }
      }));
    }
    
    // Separate approved and rejected
    const approvedIdeas = validatedIdeas.filter(i => i.approved);
    const rejectedIdeas = validatedIdeas.filter(i => !i.approved);
    
    console.log(`[IdeaBankFunnel] Results: ${approvedIdeas.length} approved, ${rejectedIdeas.length} rejected`);
    
    // =========================================================================
    // PERSIST APPROVED IDEAS
    // =========================================================================
    if (approvedIdeas.length > 0) {
      await this.persistApprovedIdeas(input, approvedIdeas);
    }
    
    // Log rejected ideas for analysis (don't persist)
    if (rejectedIdeas.length > 0) {
      console.log('[IdeaBankFunnel] Rejected ideas:');
      rejectedIdeas.forEach(idea => {
        console.log(`  - ${idea.title}: ${idea.validation.rejection_reason}`);
      });
    }
    
    return {
      success: true,
      stats: {
        generated: allRawIdeas.length,
        approved: approvedIdeas.length,
        rejected: rejectedIdeas.length
      },
      approvedIdeas,
      rejectedIdeas,
      errors: errors.length > 0 ? errors : undefined
    };
  }
  
  // ===========================================================================
  // STREAM A: Cross-Domain Applications
  // ===========================================================================
  
  private async runStreamA(
    input: IdeaFunnelInput,
    noveltyGaps: string,
    existingDomains: string
  ): Promise<RawIdea[]> {
    const inventionContext = this.buildInventionContext(input);
    
    const prompt = STREAM_A_PROMPT
      .replace('{invention_title}', input.invention.title)
      .replace('{invention_context}', inventionContext)
      .replace('{novelty_gaps}', noveltyGaps || 'No specific gaps identified')
      .replace('{existing_domains}', existingDomains || 'No specific domains identified');
    
    const result = await llmGateway.executeLLMOperation(
      { headers: input.requestHeaders || {} },
      {
        taskCode: 'LLM1_PRIOR_ART',
        stageCode: 'IDEA_BANK_GENERATION',
        prompt,
        idempotencyKey: crypto.randomUUID(),
        inputTokens: Math.ceil(prompt.length / 4),
        parameters: {
          maxOutputTokens: 3000,
          temperature: 0.7,  // Moderate creativity
          topP: 0.9
        },
        metadata: {
          source: input.source,
          stream: 'cross_domain',
          userId: input.userId
        }
      }
    );
    
    if (!result.success || !result.response) {
      console.warn('[Stream A] LLM call failed:', result.error?.message);
      return [];
    }
    
    try {
      const txt = (result.response.output || '').trim();
      const start = txt.indexOf('{');
      const end = txt.lastIndexOf('}');
      const json = start !== -1 && end !== -1 ? txt.substring(start, end + 1) : txt;
      const parsed = JSON.parse(json);
      
      const ideas = Array.isArray(parsed?.cross_domain_ideas) ? parsed.cross_domain_ideas : [];
      return ideas.map((idea: any) => ({
        title: String(idea.title || '').slice(0, 200),
        description: String(idea.description || '').slice(0, 2000),
        rationale: String(idea.rationale || '').slice(0, 500),
        target_domain: String(idea.target_domain || '').slice(0, 100),
        tags: Array.isArray(idea.tags) ? idea.tags.map((t: any) => String(t).slice(0, 60)) : [],
        source_stream: 'cross_domain' as const
      }));
    } catch (err) {
      console.warn('[Stream A] JSON parse failed:', err);
      return [];
    }
  }
  
  // ===========================================================================
  // STREAM B: Technology Combinations
  // ===========================================================================
  
  private async runStreamB(
    input: IdeaFunnelInput,
    noveltyGaps: string,
    coreCapability: string
  ): Promise<RawIdea[]> {
    const inventionContext = this.buildInventionContext(input);
    
    const prompt = STREAM_B_PROMPT
      .replace('{invention_title}', input.invention.title)
      .replace('{invention_context}', inventionContext)
      .replace('{core_capability}', coreCapability || 'Core capability not specified')
      .replace('{novelty_gaps}', noveltyGaps || 'No specific gaps identified');
    
    const result = await llmGateway.executeLLMOperation(
      { headers: input.requestHeaders || {} },
      {
        taskCode: 'LLM1_PRIOR_ART',
        stageCode: 'IDEA_BANK_GENERATION',
        prompt,
        idempotencyKey: crypto.randomUUID(),
        inputTokens: Math.ceil(prompt.length / 4),
        parameters: {
          maxOutputTokens: 3000,
          temperature: 0.7,
          topP: 0.9
        },
        metadata: {
          source: input.source,
          stream: 'tech_combination',
          userId: input.userId
        }
      }
    );
    
    if (!result.success || !result.response) {
      console.warn('[Stream B] LLM call failed:', result.error?.message);
      return [];
    }
    
    try {
      const txt = (result.response.output || '').trim();
      const start = txt.indexOf('{');
      const end = txt.lastIndexOf('}');
      const json = start !== -1 && end !== -1 ? txt.substring(start, end + 1) : txt;
      const parsed = JSON.parse(json);
      
      const ideas = Array.isArray(parsed?.tech_combination_ideas) ? parsed.tech_combination_ideas : [];
      return ideas.map((idea: any) => ({
        title: String(idea.title || '').slice(0, 200),
        description: String(idea.description || '').slice(0, 2000),
        rationale: String(idea.rationale || '').slice(0, 500),
        combined_tech: String(idea.combined_tech || '').slice(0, 100),
        tags: Array.isArray(idea.tags) ? idea.tags.map((t: any) => String(t).slice(0, 60)) : [],
        source_stream: 'tech_combination' as const
      }));
    } catch (err) {
      console.warn('[Stream B] JSON parse failed:', err);
      return [];
    }
  }
  
  // ===========================================================================
  // STREAM C: Validation Layer
  // ===========================================================================
  
  private async runStreamC(
    input: IdeaFunnelInput,
    rawIdeas: RawIdea[]
  ): Promise<ValidatedIdea[]> {
    const inventionContext = this.buildInventionContext(input);
    
    // Format ideas for validation
    const ideasJson = JSON.stringify(rawIdeas.map(idea => ({
      title: idea.title,
      description: idea.description,
      rationale: idea.rationale,
      target_domain: idea.target_domain,
      combined_tech: idea.combined_tech,
      source: idea.source_stream
    })), null, 2);
    
    const prompt = STREAM_C_VALIDATION_PROMPT
      .replace('{ideas_json}', ideasJson)
      .replace('{invention_context}', inventionContext);
    
    const result = await llmGateway.executeLLMOperation(
      { headers: input.requestHeaders || {} },
      {
        taskCode: 'LLM1_PRIOR_ART',
        stageCode: 'IDEA_BANK_GENERATION',  // Use same stage for billing
        prompt,
        idempotencyKey: crypto.randomUUID(),
        inputTokens: Math.ceil(prompt.length / 4),
        parameters: {
          maxOutputTokens: 4000,
          temperature: 0.3,  // Low temp for consistent judging
          topP: 0.9
        },
        metadata: {
          source: input.source,
          stream: 'validation',
          userId: input.userId
        }
      }
    );
    
    if (!result.success || !result.response) {
      throw new Error(result.error?.message || 'Validation LLM call failed');
    }
    
    try {
      const txt = (result.response.output || '').trim();
      const start = txt.indexOf('{');
      const end = txt.lastIndexOf('}');
      const json = start !== -1 && end !== -1 ? txt.substring(start, end + 1) : txt;
      const parsed = JSON.parse(json);
      
      const validations = Array.isArray(parsed?.validations) ? parsed.validations : [];
      
      // Match validations back to raw ideas
      return rawIdeas.map(idea => {
        const validation = validations.find(
          (v: any) => v.idea_title?.toLowerCase() === idea.title.toLowerCase()
        ) || {
          feasibility_score: 5,
          novelty_score: 5,
          coherence_score: 5,
          overall_score: 5,
          verdict: 'REJECTED',
          rejection_reason: 'Validation not found for this idea'
        };
        
        const avgScore = (
          (validation.feasibility_score || 0) +
          (validation.novelty_score || 0) +
          (validation.coherence_score || 0)
        ) / 3;
        
        const minScore = Math.min(
          validation.feasibility_score || 0,
          validation.novelty_score || 0,
          validation.coherence_score || 0
        );
        
        // Approval criteria: avg >= 6 AND no individual score below 4
        const approved = avgScore >= 6 && minScore >= 4;
        
        return {
          ...idea,
          approved,
          validation: {
            feasibility_score: validation.feasibility_score || 0,
            novelty_score: validation.novelty_score || 0,
            coherence_score: validation.coherence_score || 0,
            overall_score: avgScore,
            verdict: approved ? 'APPROVED' : 'REJECTED',
            rejection_reason: approved ? undefined : (validation.rejection_reason || `Low scores: avg=${avgScore.toFixed(1)}, min=${minScore}`),
            improvement_suggestions: validation.improvement_suggestions
          }
        };
      });
    } catch (err) {
      console.warn('[Stream C] JSON parse failed:', err);
      throw err;
    }
  }
  
  // ===========================================================================
  // PERSISTENCE
  // ===========================================================================
  
  private async persistApprovedIdeas(
    input: IdeaFunnelInput,
    approvedIdeas: ValidatedIdea[]
  ): Promise<void> {
    console.log(`[IdeaBankFunnel] Persisting ${approvedIdeas.length} approved ideas...`);
    
    // Get user for idea bank service
    const user = await prisma.user.findUnique({
      where: { id: input.userId }
    });
    
    if (!user) {
      console.error('[IdeaBankFunnel] User not found:', input.userId);
      return;
    }
    
    // Determine the reference ID for linking
    const referenceId = input.patentId || input.searchRunId || undefined;
    
    for (const idea of approvedIdeas) {
      try {
        const extractedIdea = {
          title: idea.title,
          description: idea.description,
          abstract: idea.rationale,
          domainTags: idea.tags,
          technicalField: idea.target_domain || idea.combined_tech || 'AI-Generated',
          keyFeatures: [
            idea.source_stream === 'cross_domain' 
              ? `Cross-domain application: ${idea.target_domain}` 
              : `Technology combination: ${idea.combined_tech}`
          ],
          potentialApplications: ['Generated from prior art analysis'],
          noveltyScore: idea.validation.overall_score / 10,  // Normalize to 0-1
          metadata: {
            source: input.source,
            stream: idea.source_stream,
            validation_scores: idea.validation,
            generated_at: new Date().toISOString()
          }
        };
        
        await this.ideaBankService.addIdeaFromNoveltySearch(
          extractedIdea,
          user,
          referenceId
        );
        
        console.log(`[IdeaBankFunnel] ✅ Persisted: ${idea.title}`);
      } catch (err) {
        console.error(`[IdeaBankFunnel] ❌ Failed to persist: ${idea.title}`, err);
      }
    }
  }
  
  // ===========================================================================
  // HELPERS
  // ===========================================================================
  
  private buildInventionContext(input: IdeaFunnelInput): string {
    const parts: string[] = [];
    
    if (input.invention.abstract) {
      parts.push(`Abstract: ${input.invention.abstract}`);
    }
    if (input.invention.searchQuery) {
      parts.push(`Search Query: ${input.invention.searchQuery}`);
    }
    if (input.invention.features && input.invention.features.length > 0) {
      parts.push(`Key Features:\n${input.invention.features.map(f => `- ${f}`).join('\n')}`);
    }
    if (input.invention.claims) {
      // Truncate claims if too long
      const claimsPreview = input.invention.claims.length > 500 
        ? input.invention.claims.substring(0, 500) + '...'
        : input.invention.claims;
      parts.push(`Claims Preview: ${claimsPreview}`);
    }
    
    return parts.join('\n\n') || 'No additional context available';
  }
  
  private extractNoveltyGaps(priorArt: PriorArtAnalysisItem[]): string {
    // Extract what makes our invention unique from the prior art analysis
    const gaps = priorArt
      .filter(p => p.detailedAnalysis?.novelty_comparison)
      .map(p => `vs ${p.pn}: ${p.detailedAnalysis.novelty_comparison}`)
      .slice(0, 5);  // Limit to top 5
    
    if (gaps.length === 0) {
      // Fallback: extract from irrelevant_parts (what our invention has that they don't)
      const irrelevant = priorArt
        .flatMap(p => p.detailedAnalysis?.irrelevant_parts || [])
        .filter((v, i, arr) => arr.indexOf(v) === i)  // Unique
        .slice(0, 5);
      
      if (irrelevant.length > 0) {
        return `Our unique elements not found in prior art:\n${irrelevant.map(i => `- ${i}`).join('\n')}`;
      }
    }
    
    return gaps.join('\n') || 'No specific novelty gaps identified';
  }
  
  private extractDomains(priorArt: PriorArtAnalysisItem[]): string {
    // Extract domains/fields from prior art titles
    const titles = priorArt.map(p => p.title).filter(Boolean);
    
    if (titles.length === 0) return 'No specific domains identified';
    
    return `Prior art exists in these areas:\n${titles.slice(0, 5).map(t => `- ${t}`).join('\n')}`;
  }
  
  private extractCoreCapability(input: IdeaFunnelInput): string {
    // Try to extract the core capability from invention context
    if (input.invention.features && input.invention.features.length > 0) {
      return input.invention.features.slice(0, 3).join('; ');
    }
    if (input.invention.abstract) {
      return input.invention.abstract.substring(0, 300);
    }
    return input.invention.title;
  }
}

// Export singleton instance
export const ideaBankFunnel = new IdeaBankFunnelService();

