/**
 * LIVE test: verifies the Stage 0 LLM actually emits `google_concept_groups`
 * per the V2 prompt, and that the pipeline wiring turns them into a
 * professional boolean Google Patents query.
 *
 * Runs only when an LLM API key is configured (same convention as
 * patentsview-provider.live.test.ts). Makes ONE real LLM call; no DB writes,
 * no SerpAPI calls.
 */
import { describe, expect, test } from 'vitest'
import { NOVELTY_SEARCH_NORMALIZATION_PROMPT_V2, NoveltySearchService } from '@/lib/novelty-search-service'
import { buildGooglePatentsQueryForTests } from '@/lib/patent-search/providers/google-patents-provider'
import type { PatentProviderSearchRequest, PatentSearchConceptGroup } from '@/lib/patent-search/types'

const OPENAI_KEY = process.env.OPENAI_API_KEY || ''
const GOOGLE_KEY = process.env.GOOGLE_AI_API_KEY || process.env.GOOGLE_API_KEY || ''
// Costs real LLM tokens (~40s) — opt in explicitly:
//   RUN_LIVE_LLM_TESTS=1 npx vitest run src/lib/novelty-stage0-google-groups.live.test.ts
const hasKey = Boolean((OPENAI_KEY || GOOGLE_KEY) && process.env.RUN_LIVE_LLM_TESTS === '1')

const TITLE = 'Solar-powered cold storage with produce-adaptive ventilation'
const DISCLOSURE = `A solar-powered cold storage container for farm produce. Phase-change material panels
store cooling generated by a solar-driven compressor during daylight and release it overnight.
An ethylene gas sensor detects the ripening stage of the stored produce. A controller adjusts
ventilation louver position and humidity misting frequency based on the detected ripening stage
and produce type, extending shelf life without any grid power connection.`

async function callOpenAI(prompt: string): Promise<{ model: string; output: string } | null> {
  const candidates = [process.env.STAGE0_TEST_MODEL, 'gpt-5-mini', 'gpt-4o-mini', 'gpt-4o'].filter(Boolean) as string[]
  for (const model of candidates) {
    try {
      const isReasoning = model.startsWith('gpt-5') || /^o\d/.test(model)
      const body: any = {
        model,
        messages: [{ role: 'user', content: prompt }],
      }
      if (isReasoning) body.max_completion_tokens = 6000
      else { body.max_tokens = 4000; body.temperature = 0.2 }
      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: { Authorization: `Bearer ${OPENAI_KEY}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      const json: any = await response.json().catch(() => ({}))
      const output = json?.choices?.[0]?.message?.content
      if (response.ok && output) return { model, output }
      console.warn(`[live-test] OpenAI model ${model} unavailable: ${response.status} ${JSON.stringify(json?.error?.message || '').slice(0, 160)}`)
    } catch (error) {
      console.warn(`[live-test] OpenAI model ${model} failed:`, error instanceof Error ? error.message : error)
    }
  }
  return null
}

async function callGemini(prompt: string): Promise<{ model: string; output: string } | null> {
  const candidates = ['gemini-3.5-flash', 'gemini-2.5-flash', 'gemini-2.0-flash']
  for (const model of candidates) {
    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-goog-api-key': GOOGLE_KEY },
          body: JSON.stringify({
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            generationConfig: { maxOutputTokens: 4000, temperature: 0.2 },
          }),
        },
      )
      const json: any = await response.json().catch(() => ({}))
      const output = (json?.candidates?.[0]?.content?.parts || []).map((p: any) => p?.text).filter(Boolean).join('\n')
      if (response.ok && output) return { model, output }
      console.warn(`[live-test] Gemini model ${model} unavailable: ${response.status}`)
    } catch (error) {
      console.warn(`[live-test] Gemini model ${model} failed:`, error instanceof Error ? error.message : error)
    }
  }
  return null
}

describe.skipIf(!hasKey)('Stage 0 LLM emits Google concept groups (live)', () => {
  test('real LLM output flows into a boolean Google Patents query', async () => {
    const prompt = NOVELTY_SEARCH_NORMALIZATION_PROMPT_V2
      .replace('{title}', TITLE)
      .replace('{rawIdea}', DISCLOSURE)

    const result = (OPENAI_KEY && await callOpenAI(prompt)) || (GOOGLE_KEY && await callGemini(prompt)) || null
    expect(result, 'no configured LLM produced output — check API keys/models').toBeTruthy()
    const { model, output } = result as { model: string; output: string }

    const service = new (NoveltySearchService as any)()
    const parsed = service.parseLLMResponse(output)
    expect(parsed, 'LLM response was not parseable JSON').toBeTruthy()

    // ---- what the LLM produced ----
    console.log('\n================ STAGE 0 LIVE OUTPUT ================')
    console.log('LLM model:          ', model)
    console.log('searchQuery:        ', parsed.searchQuery)
    console.log('invention_features: ', JSON.stringify(parsed.invention_features, null, 2))
    console.log('search_exclusions:  ', JSON.stringify(parsed.search_exclusions))
    console.log('google_concept_groups (raw):')
    console.log(JSON.stringify(parsed.google_concept_groups, null, 2))

    // ---- the new pipeline path: normalize → wire → build ----
    const groups: PatentSearchConceptGroup[] = service.normalizeGoogleConceptGroups(parsed.google_concept_groups)
    expect(groups.length, 'LLM did not emit usable concept groups').toBeGreaterThanOrEqual(2)
    for (const group of groups) {
      expect(group.terms.length).toBeGreaterThanOrEqual(1)
      expect(group.terms.length).toBeLessThanOrEqual(5)
      for (const term of group.terms) {
        expect(term).not.toMatch(/["()*?]/) // builder-hostile syntax must be stripped
      }
    }

    const exclusions: string[] = Array.isArray(parsed.search_exclusions) ? parsed.search_exclusions.filter(Boolean) : []
    const conceptGroups: PatentSearchConceptGroup[] = [
      ...groups,
      ...(exclusions.length ? [{ label: 'stage0-exclusions', terms: exclusions.slice(0, 4), excluded: true }] : []),
    ]
    const requiredCount = conceptGroups.filter(g => !g.excluded && g.required !== false).length

    const request = {
      searchMode: 'intelligent',
      query: parsed.searchQuery,
      title: TITLE,
      inventionText: DISCLOSURE,
      filters: {},
      jurisdictions: ['IN'],
      sourceMode: 'PQAI_PLUS_INDIAN',
      llmExpansion: false,
      limit: 20,
      queryPlan: {
        originalQuery: parsed.searchQuery,
        normalizedQuery: parsed.searchQuery,
        searchQuery: parsed.searchQuery,
        semanticQuery: parsed.searchQuery,
        inventionFeatures: parsed.invention_features || [],
        technicalKeywords: [],
        synonyms: [],
        mustHaveTerms: [],
        excludedTerms: exclusions,
        cpcCodes: [],
        ipcCodes: [],
        classificationHints: [],
        patentSearchConceptGroups: conceptGroups,
        ...(requiredCount >= 2 ? { searchPrecision: 'refined' as const } : {}),
        fieldFilters: {},
        explicitFilters: {},
        searchVariants: [],
        llmExpanded: false,
        confidence: 0.9,
        warnings: [],
      },
    } as unknown as PatentProviderSearchRequest

    const refinedQuery = buildGooglePatentsQueryForTests(request)
    const broadQuery = buildGooglePatentsQueryForTests({
      ...request,
      queryPlan: { ...request.queryPlan, searchPrecision: 'broad' },
    } as PatentProviderSearchRequest)

    console.log('\n---- FINAL GOOGLE PATENTS QUERIES ----')
    console.log('refined (dispatched):', refinedQuery)
    console.log('broad (fallback):    ', broadQuery)
    console.log('=====================================================\n')

    expect(refinedQuery).toContain(' AND ')          // AND-of-OR-groups precision
    expect(refinedQuery).toMatch(/"[^"]+"/)          // quoted multiword phrases
    expect(broadQuery.length).toBeGreaterThan(0)     // fallback always available
  }, 120_000)
})
