// Built-in claim-rule defaults for the fourteen offices that have drafting
// profiles, plus a neutral profile for anything else.
//
// The runtime resolves rules as: built-in default for the office, then the
// structured fields the DB profile carries (see resolve.ts). The defaults exist
// so claim form never depends on which profile JSON was last imported, and so
// a jurisdiction the DB knows nothing about still gets neutral, defensible
// form rather than US form by accident.
//
// Cells marked "counsel" in the plan (CA and ZA medical forms, BR and ZA CRM
// acceptance, RU treatment methods, AU omnibus) are best current practice and
// are overridable per country in the profile without a deploy.

import { CLAIM_RULES_VERSION, type ClaimRuleProfile } from './types'

type DefaultInput = Omit<ClaimRuleProfile, 'rulesVersion' | 'notes' | 'requireSupportInDescription'> &
  Partial<Pick<ClaimRuleProfile, 'requireSupportInDescription' | 'notes'>>

const EP_EXCLUSIONS = [
  'discovery',
  'mathematical_method',
  'mental_act_business_scheme',
  'computer_program_as_such',
  'presentation_of_information',
  'method_of_treatment',
  'diagnostic_method',
  'plant_animal_variety',
]

function profile(input: DefaultInput): ClaimRuleProfile {
  return {
    rulesVersion: CLAIM_RULES_VERSION,
    requireSupportInDescription: true,
    notes: [],
    ...input,
  }
}

export const GENERIC_CLAIM_RULES: ClaimRuleProfile = profile({
  jurisdiction: 'XX',
  office: 'Patent Office',
  language: 'en',
  dependentClaimPhrase: 'according_to',
  multipleDependencyMode: 'alternative_only',
  multiOnMultiProhibited: true,
  twoPartForm: 'optional',
  characterisedSpelling: 'z',
  singleIndependentPerCategory: false,
  referenceNumerals: 'permitted',
  omnibusClaims: 'forbidden',
  claimOrdering: 'grouped_by_category',
  preferredTransitions: ['comprising'],
  discouragedTransitions: [],
  forbiddenPhrases: [],
  useClaims: 'allowed',
  medicalMethodClaims: 'allowed_with_for_use_mirror',
  crmClaimForm: 'program_and_medium',
  softwareEligibilityDoctrine: 'technical_character',
  excludedSubjectMatter: [],
  productByProcess: 'allowed',
  freeTotalClaims: null,
  freeIndependentClaims: null,
  defaultClaimBudget: 15,
  feeNote: '',
  unityStandard: 'single general inventive concept',
})

export const CLAIM_RULE_DEFAULTS: Record<string, ClaimRuleProfile> = {
  US: profile({
    jurisdiction: 'US',
    office: 'United States Patent and Trademark Office',
    language: 'en',
    dependentClaimPhrase: 'of',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'discouraged',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'optional',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising'],
    discouragedTransitions: ['consisting of'],
    forbiddenPhrases: [],
    useClaims: 'not_allowed',
    medicalMethodClaims: 'allowed',
    crmClaimForm: 'non_transitory_medium',
    softwareEligibilityDoctrine: 'us_101',
    excludedSubjectMatter: ['abstract_idea', 'law_of_nature', 'natural_phenomenon'],
    productByProcess: 'allowed',
    freeTotalClaims: 20,
    freeIndependentClaims: 3,
    defaultClaimBudget: 20,
    feeNote: 'The basic fee covers 20 total claims and 3 independent claims; each further claim and each further independent claim carries an excess-claim fee (37 CFR 1.16(h)-(i)), and any multiple dependent claim adds a surcharge (37 CFR 1.16(j)).',
    unityStandard: 'US restriction practice (35 USC 121): claims to independent and distinct inventions may be restricted.',
  }),

  EP: profile({
    jurisdiction: 'EP',
    office: 'European Patent Office',
    language: 'en',
    dependentClaimPhrase: 'according_to',
    multipleDependencyMode: 'any',
    multiOnMultiProhibited: false,
    twoPartForm: 'preferred',
    characterisedSpelling: 's',
    singleIndependentPerCategory: true,
    referenceNumerals: 'recommended_if_drawings',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising', 'characterised in that'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'for_use_only',
    crmClaimForm: 'program_and_medium',
    softwareEligibilityDoctrine: 'ep_technical_character',
    excludedSubjectMatter: EP_EXCLUSIONS,
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 15,
    freeIndependentClaims: null,
    defaultClaimBudget: 15,
    feeNote: 'Claims fees are payable for the 16th and each subsequent claim, at a substantially higher rate from the 51st (Rule 45 EPC; RFees Art. 2(1) item 15). Multiple dependent claims are not penalised.',
    unityStandard: 'single general inventive concept (Article 82, Rule 44 EPC)',
  }),

  PCT: profile({
    jurisdiction: 'PCT',
    office: 'International Bureau of WIPO (PCT)',
    language: 'en',
    dependentClaimPhrase: 'according_to',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'optional',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'recommended_if_drawings',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'allowed_with_for_use_mirror',
    crmClaimForm: 'program_and_medium',
    softwareEligibilityDoctrine: 'pct_technical_character',
    excludedSubjectMatter: [],
    productByProcess: 'allowed',
    freeTotalClaims: null,
    freeIndependentClaims: null,
    defaultClaimBudget: 15,
    feeNote: 'The international phase charges no claim fees (the international fee counts sheets over 30). National phases do: the EPO charges from the 16th claim and the USPTO beyond 20 total or 3 independent claims, so a set of at most 15 claims with at most 3 independent claims enters every major office fee-free.',
    unityStandard: 'single general inventive concept (PCT Rule 13)',
  }),

  IN: profile({
    jurisdiction: 'IN',
    office: 'Indian Patent Office',
    language: 'en',
    dependentClaimPhrase: 'as_claimed_in',
    multipleDependencyMode: 'any',
    multiOnMultiProhibited: false,
    twoPartForm: 'optional',
    characterisedSpelling: 's',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising', 'including'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'not_allowed',
    medicalMethodClaims: 'composition_only',
    crmClaimForm: 'not_recommended',
    softwareEligibilityDoctrine: 'in_3k',
    excludedSubjectMatter: [
      's3c_discovery',
      's3d_new_form_of_known_substance',
      's3e_mere_admixture',
      's3i_medical_treatment_or_diagnosis',
      's3k_program_algorithm_business_or_mathematical_method',
      's3m_mental_act_or_game',
      's3n_presentation_of_information',
      's3p_traditional_knowledge',
    ],
    productByProcess: 'allowed',
    freeTotalClaims: 10,
    freeIndependentClaims: null,
    defaultClaimBudget: 10,
    feeNote: 'The basic fee covers 10 claims; each claim beyond 10 carries a per-claim fee (First Schedule, Patents Rules 2003).',
    unityStandard: 'single invention or a group linked by a single inventive concept (Section 10(5), Patents Act 1970)',
  }),

  CN: profile({
    jurisdiction: 'CN',
    office: 'China National Intellectual Property Administration',
    language: 'en',
    dependentClaimPhrase: 'characterized',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'required',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising', 'characterized in that'],
    discouragedTransitions: ['consisting essentially of'],
    forbiddenPhrases: ['as described in the description', 'as shown in the drawings'],
    useClaims: 'allowed_as_method',
    medicalMethodClaims: 'swiss_type_only',
    crmClaimForm: 'medium_and_program_product',
    softwareEligibilityDoctrine: 'cn_technical_solution',
    excludedSubjectMatter: ['discovery', 'rules_and_methods_for_mental_activities', 'medical_treatment_or_diagnosis', 'animal_plant_variety'],
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 10,
    freeIndependentClaims: null,
    defaultClaimBudget: 10,
    feeNote: 'The basic filing fee covers 10 claims; an additional fee applies to each claim beyond 10, counted over independent and dependent claims together.',
    unityStandard: 'single general inventive concept (Article 31 Patent Law; Implementing Regulations)',
  }),

  JP: profile({
    jurisdiction: 'JP',
    office: 'Japan Patent Office',
    language: 'en',
    dependentClaimPhrase: 'according_to',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'optional',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'not_allowed',
    medicalMethodClaims: 'composition_only',
    crmClaimForm: 'program_and_medium',
    softwareEligibilityDoctrine: 'jp_program_product',
    excludedSubjectMatter: ['not_a_creation_using_a_law_of_nature', 'mental_act_or_business_scheme_as_such', 'medical_treatment_of_humans'],
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 0,
    freeIndependentClaims: null,
    defaultClaimBudget: 15,
    feeNote: 'Examination-request and annuity fees are charged per claim from the first claim, so every claim carries a recurring cost; there is no fee-free block.',
    unityStandard: 'single general inventive concept (Article 37 Patent Act)',
  }),

  KR: profile({
    jurisdiction: 'KR',
    office: 'Korean Intellectual Property Office',
    language: 'en',
    dependentClaimPhrase: 'according_to',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'optional',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising', 'including'],
    discouragedTransitions: ['consisting essentially of'],
    forbiddenPhrases: ['as described in the description', 'as shown in the drawings'],
    useClaims: 'not_allowed',
    medicalMethodClaims: 'composition_only',
    crmClaimForm: 'program_stored_in_medium',
    softwareEligibilityDoctrine: 'kr_program_medium',
    excludedSubjectMatter: ['not_a_creation_using_a_law_of_nature', 'mental_act_or_business_scheme_as_such', 'medical_treatment_of_humans'],
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 0,
    freeIndependentClaims: null,
    defaultClaimBudget: 10,
    feeNote: 'The examination-request fee and every annuity include a per-claim add-on counted from the first claim, so each claim carries a lifetime cost.',
    unityStandard: 'single general inventive concept (Article 45 Patent Act)',
  }),

  UK: profile({
    jurisdiction: 'UK',
    office: 'UK Intellectual Property Office',
    language: 'en',
    dependentClaimPhrase: 'as_claimed_in',
    multipleDependencyMode: 'any',
    multiOnMultiProhibited: false,
    twoPartForm: 'optional',
    characterisedSpelling: 's',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'for_use_only',
    crmClaimForm: 'program_and_medium',
    softwareEligibilityDoctrine: 'uk_aerotel',
    excludedSubjectMatter: EP_EXCLUSIONS,
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 25,
    freeIndependentClaims: null,
    defaultClaimBudget: 20,
    feeNote: 'An excess-claims fee is charged for each claim over 25 at the search stage.',
    unityStandard: 'single invention or a group linked by a single inventive concept (s.14(5)(d) Patents Act 1977)',
  }),

  DE: profile({
    jurisdiction: 'DE',
    office: 'Deutsches Patent- und Markenamt',
    language: 'en',
    dependentClaimPhrase: 'according_to',
    multipleDependencyMode: 'any',
    multiOnMultiProhibited: false,
    twoPartForm: 'preferred',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'recommended_if_drawings',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising', 'characterized in that'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'for_use_only',
    crmClaimForm: 'program_and_medium',
    softwareEligibilityDoctrine: 'de_technical_character',
    excludedSubjectMatter: EP_EXCLUSIONS,
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 10,
    freeIndependentClaims: null,
    defaultClaimBudget: 10,
    feeNote: 'The filing fee covers 10 claims; a surcharge applies from the 11th claim.',
    unityStandard: 'single general inventive concept (§34(5) PatG)',
  }),

  AU: profile({
    jurisdiction: 'AU',
    office: 'IP Australia',
    language: 'en',
    dependentClaimPhrase: 'according_to',
    multipleDependencyMode: 'any',
    multiOnMultiProhibited: false,
    twoPartForm: 'optional',
    characterisedSpelling: 's',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'allowed',
    crmClaimForm: 'medium_only',
    softwareEligibilityDoctrine: 'au_manner_of_manufacture',
    excludedSubjectMatter: ['mere_scheme_or_business_method', 'mere_information', 'human_beings_and_processes_for_their_generation'],
    productByProcess: 'allowed',
    freeTotalClaims: 20,
    freeIndependentClaims: null,
    defaultClaimBudget: 20,
    feeNote: 'Excess-claim fees apply to each claim over 20 at acceptance.',
    unityStandard: 'single invention (s.40(2)(b) Patents Act 1990)',
  }),

  CA: profile({
    jurisdiction: 'CA',
    office: 'Canadian Intellectual Property Office',
    language: 'en',
    dependentClaimPhrase: 'of',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: false,
    twoPartForm: 'optional',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['comprising'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'use_claim_only',
    crmClaimForm: 'medium_only',
    softwareEligibilityDoctrine: 'ca_physicality',
    excludedSubjectMatter: ['method_of_medical_treatment', 'abstract_idea_without_physicality', 'higher_life_form'],
    productByProcess: 'allowed',
    freeTotalClaims: 20,
    freeIndependentClaims: null,
    defaultClaimBudget: 20,
    feeNote: 'Excess-claim fees apply to each claim over 20 at the request for examination and at grant.',
    unityStandard: 'one invention only (s.36 Patent Act)',
  }),

  BR: profile({
    jurisdiction: 'BR',
    office: 'Instituto Nacional da Propriedade Industrial',
    language: 'pt-BR',
    dependentClaimPhrase: 'characterized',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'required',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['caracterizado por'],
    discouragedTransitions: [],
    forbiddenPhrases: ['como descrito no relatório', 'como mostrado nos desenhos', 'aproximadamente'],
    useClaims: 'allowed',
    medicalMethodClaims: 'swiss_type_only',
    crmClaimForm: 'medium_only',
    softwareEligibilityDoctrine: 'br_technical_effect',
    excludedSubjectMatter: ['discovery', 'business_method', 'computer_program_per_se', 'presentation_of_information', 'method_of_medical_treatment', 'natural_biological_material'],
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 10,
    freeIndependentClaims: null,
    defaultClaimBudget: 10,
    feeNote: 'Escalating fees apply to each claim beyond 10.',
    unityStandard: 'single inventive concept (Art. 22 LPI)',
  }),

  ZA: profile({
    jurisdiction: 'ZA',
    office: 'Companies and Intellectual Property Commission',
    language: 'en',
    dependentClaimPhrase: 'as_claimed_in',
    multipleDependencyMode: 'any',
    multiOnMultiProhibited: false,
    twoPartForm: 'optional',
    characterisedSpelling: 's',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'customary',
    claimOrdering: 'decreasing_scope',
    preferredTransitions: ['comprising', 'including'],
    discouragedTransitions: [],
    forbiddenPhrases: [],
    useClaims: 'allowed',
    medicalMethodClaims: 'swiss_type_only',
    crmClaimForm: 'medium_only',
    softwareEligibilityDoctrine: 'za_as_such',
    excludedSubjectMatter: ['discovery', 'mathematical_method', 'scheme_rule_or_method_for_business_or_a_game', 'computer_program_as_such', 'presentation_of_information', 'method_of_treatment', 'plant_animal_variety'],
    productByProcess: 'allowed',
    freeTotalClaims: null,
    freeIndependentClaims: null,
    defaultClaimBudget: 20,
    feeNote: 'No excess-claim fees.',
    unityStandard: 'one invention (s.32(3)(a) and 32(4) Patents Act 1978)',
  }),

  RU: profile({
    jurisdiction: 'RU',
    office: 'Rospatent',
    language: 'ru',
    dependentClaimPhrase: 'characterized',
    multipleDependencyMode: 'alternative_only',
    multiOnMultiProhibited: true,
    twoPartForm: 'required',
    characterisedSpelling: 'z',
    singleIndependentPerCategory: false,
    referenceNumerals: 'permitted',
    omnibusClaims: 'forbidden',
    claimOrdering: 'grouped_by_category',
    preferredTransitions: ['отличающийся тем, что'],
    discouragedTransitions: [],
    forbiddenPhrases: ['примерно', 'например', 'и тому подобное'],
    useClaims: 'allowed',
    medicalMethodClaims: 'allowed',
    crmClaimForm: 'medium_only',
    softwareEligibilityDoctrine: 'ru_technical_result',
    excludedSubjectMatter: ['discovery', 'mathematical_method', 'rules_of_games_or_business', 'computer_program_as_such', 'presentation_of_information', 'plant_animal_variety'],
    productByProcess: 'only_if_necessary',
    freeTotalClaims: 10,
    freeIndependentClaims: 1,
    defaultClaimBudget: 10,
    feeNote: 'Fees apply per claim beyond 10 and per independent claim beyond the first.',
    unityStandard: 'single inventive concept (Art. 1375(2) Civil Code)',
  }),
}

/** Codes that resolve to another profile's rules. */
export const CLAIM_RULE_ALIASES: Record<string, string> = {
  WO: 'PCT',
  WIPO: 'PCT',
  EPO: 'EP',
  GB: 'UK',
  USA: 'US',
}

export function canonicalClaimRuleCode(jurisdiction: string | null | undefined): string {
  const code = String(jurisdiction || '').trim().toUpperCase()
  return CLAIM_RULE_ALIASES[code] || code
}
